version: '3'

services:
  web:
    build:
      context: .

    command: /code/venv/bin/gunicorn -b 0.0.0.0:8888 cardealer.wsgi:application

    volumes:
      - .:/code

    ports:
      - "8888:8888"

    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'garbin'
      MYSQL_USER: 'dbmasteruser'
      MYSQL_PASSWORD: 'KL59L8596'
      MYSQL_ROOT_PASSWORD: 'KL59L8596'
      MYSQL_HOST: 'ls-f5d32fe56a97e29caf4e2c35edb8654241527639.cpi48a8m27mq.ap-south-1.rds.amazonaws.com'
    ports:
      - "3306:3306"
