# Generated by Django 5.0.1 on 2024-01-24 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='features',
        ),
    ]
