# Generated by Django 5.0.1 on 2024-01-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state',
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('3', '3'), ('5', '5')], max_length=10),
        ),
    ]
