# Generated by Django 5.0.1 on 2024-01-26 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='miles',
            new_name='kilometers',
        ),
        migrations.RemoveField(
            model_name='car',
            name='vin_no',
        ),
    ]
