# Generated by Django 5.0.1 on 2024-01-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_miles_car_kilometers_remove_car_vin_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='city',
        ),
    ]
