# Generated by Django 5.0.1 on 2024-01-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_car_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('PETROL', 'petrol'), ('DIESEL', 'diesel'), ('EV', 'ev')], max_length=10),
        ),
    ]
